sudo: false
dist: xenial
language: python

branches:
  only:
    - "master"

install:
  - pip install tox coveralls

matrix:
  include:
    - python: 3.7
      env: TOXENV=linting
    - python: 3.7
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  email: false
