"""Exceptions for dcrw.

All exceptions generated by this library will descend from DcError.
"""


class DcError(Exception):
    """ Base Exception for this module. """
    pass


class ConstructError(DcError):
    """ Error constructing an object. """
    pass


class ParseError(DcError):
    """ Error parsing a DC element. """
    pass
