"""Exceptions for yapremisrw.

All exceptions generated by this library will descend from PremisError.
"""


class PremisError(Exception):
    """ Base Exception for this module. """
    pass


class ConstructError(PremisError):
    """ Error constructing an object. """
    pass


class ParseError(PremisError):
    """ Error parsing a PREMIS element. """
    pass
