---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  test:
    name: "Test Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: "Run tox"
        run: |
          tox -- --cov metsrw --cov-report xml:coverage.xml
      - name: "Upload coverage report"
        if: github.repository == 'artefactual-labs/mets-reader-writer'
        uses: "codecov/codecov-action@v4"
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e linting
  docs:
    name: "Docs"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e docs
